{% set python_min = "3.10" %}
{% set name = "txl-image-viewer" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_image_viewer-{{ version }}.tar.gz
  sha256: ccb68d315379af48c0554694981eecfc9c129f7f8fb0d535ab17897e18b9fa3a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2
    - textual-imageview >=0.1.1

test:
  requires:
    - pip
  commands:
    - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_image_viewer

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/txl_image_viewer
  summary: TXL plugin for an image viewer
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/txl_image_viewer
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
