{% set python_min = "3.10" %}
{% set name = "txl-image-viewer" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_image_viewer-{{ version }}.tar.gz
  sha256: 7cc22a5726cfc9082d0ec22912ff5c8fcbdbe65d580ecf9b7fe806f9d670912d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - textual-imageview >=0.1.1

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_image_viewer

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/txl_image_viewer
  summary: TXL plugin for an image viewer
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/txl_image_viewer
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
